config/routes.rb
Rails.application.routes.draw do
  get '/home'    => 'web_pages#show', id: 1
  get '/privacy'    => 'web_pages#show', id: 2
  get '/terms'    => 'web_pages#show', id: 3
  get '/about'    => 'web_pages#show', id: 4

  devise_for :users
  resources :users

  resources :product_person_maps

  resources :document_person_maps

  resources :web_pages

  resources :grants

  resources :projects

  resources :courses

  resources :course_offerings

  resources :news_events

  resources :products

  resources :product_categories

  resources :documents

  resources :document_categories

  resources :people

  resources :person_categories

  resources :research_areas

  root 'web_pages#home'

end

app/models/document.rb
class Document < ActiveRecord::Base
  belongs_to :document_category
  has_many :document_person_maps
  has_many :people, :through => :document_person_maps
  has_and_belongs_to_many :projects
  has_and_belongs_to_many :research_areas
  has_and_belongs_to_many :grants
  belongs_to :main_research_area, :class_name => "ResearchArea", :foreign_key => "main_research_area_id"

  validates :tryear, presence: {message: ": Missing year"}
  validates :trmonth, presence: {message: ": Missing month"}
  validates :trnumber, presence: {message: ": Missing number"}
  validates :title, presence: {message: ": Missing title"}
  validates :ispublic, presence: {message: ": Missing public/nonpublic status"}
  validates :islabdocument, presence: {message: ": Missing lab status"}

  validates :urlpdfpaper,  :urlsrcpaper,  :urlpdfpresentation,  :urlsrcpresentation,
            :urlavmedia,  :urldoi,  :urlpublisher,  :urlgooglescholar,  :urlciteseer,
            allow_nil: true, format: {with: URI::regexp(%w(http https)),  message: ": URL is malformed"}

  validates :pubvol, allow_nil: true, format: {with:  /\A((\d+)|([IVXLCDM]+))?\z/, message:  ": Volume is in wrong format"}
  validates :pubnum, allow_nil: true, format: {with:  /\A\d*\z/, message:  ": Number start is in wrong format"}
  validates :pubnum_end, allow_nil: true, format: {with:  /\A\d*\z/, message:  ": Number end is in wrong format"}
  validates :pubpagecount, allow_nil: true, format: {with:  /\A\d*\z/, message:  ": Page Count is in wrong format"}
  validates :pubpagefirst, allow_nil: true, format: {with:  /\A((\d+)|([IVXLCDM]+)|([ivxlcdm]+))?\z/, message:  ": Page number start is in wrong format"}
  validates :pubpagelast, allow_nil: true, format: {with:  /\A((\d+)|([IVXLCDM]+)|([ivxlcdm]+))?\z/, message:  ": Page number end is in wrong format"}

  validates :tryear, numericality: {only_integer: true, greater_than: 1970, less_than: 2070, message: ": Document year does not seem right"}
  validates :trmonth, numericality: {only_integer: true, greater_than: 0, less_than: 13, message: ": Document month does not seem right"}

  def self.get_trnumber(year, month)
    results = Document.find_by_sql "SELECT MAX(trnumber) AS trnumber FROM documents d WHERE d.tryear=#{year} AND d.trmonth=#{month}"
    return ((results && results[0] && results[0].trnumber) ? (results[0].trnumber + 1) : 1)
  end

  def self.find_all_in_priorityrange_sorted_by_date(min_priority=0,max_priority=1,count=5)
    Document.find_by_sql "SELECT d.* FROM documents d, documentcategories dc WHERE d.documentcategory_id = dc.id AND dc.priority >= #{min_priority} AND dc.priority <= #{max_priority} ORDER BY pubdate DESC LIMIT #{count}"
  end

end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :set_document, only: [:show, :edit, :update, :destroy]

  # GET /documents
  # GET /documents.json
  def index
    @documents = Document.all
  end

  # GET /documents/1
  # GET /documents/1.json
  def show
  end

  # GET /documents/new
  def new
    @document = Document.new
  end

  # GET /documents/1/edit
  def edit
  end

  # POST /documents
  # POST /documents.json
  def create
    @document = Document.new(document_params)

    respond_to do |format|
      if @document.save
        format.html { redirect_to @document, notice: 'Document was successfully created.' }
        format.json { render :show, status: :created, location: @document }
      else
        format.html { render :new }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /documents/1
  # PATCH/PUT /documents/1.json
  def update
    respond_to do |format|
      if @document.update(document_params)
        format.html { redirect_to @document, notice: 'Document was successfully updated.' }
        format.json { render :show, status: :ok, location: @document }
      else
        format.html { render :edit }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    @document.destroy
    respond_to do |format|
      format.html { redirect_to documents_url, notice: 'Document was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_document
      @document = Document.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def document_params
      params.require(:document).permit(:tryear, :trmonth, :trnumber, :title, :abstract, :filename, :file, :urlpdfpaper, :urlsrcpaper, :urlpdfpresentation, :urlsrcpresentation, :urlavmedia, :urldoi, :urlpublisher, :urlgooglescholar, :urlciteseer, :pubin, :pubvol, :pubnum, :pubnum_end, :pubpagefirst, :pubpagelast, :pubpagecount, :pubdate, :pubdate_end, :pubplace, :publisher, :ispublic, :islabdocument, :miscattributes, :document_category_id, :main_research_area_id)
    end
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_form.html.erb
<%= form_for(@document) do |f| %>
  <% if @document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@document.errors.count, "error") %> prohibited this document from being saved:</h2>

      <ul>
      <% @document.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tryear %><br>
    <%= f.number_field :tryear %>
  </div>
  <div class="field">
    <%= f.label :trmonth %><br>
    <%= f.number_field :trmonth %>
  </div>
  <div class="field">
    <%= f.label :trnumber %><br>
    <%= f.number_field :trnumber %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :abstract %><br>
    <%= f.text_area :abstract %>
  </div>
  <div class="field">
    <%= f.label :filename %><br>
    <%= f.text_field :filename %>
  </div>
  <div class="field">
    <%= f.label :file %><br>
    <%= f.text_field :file %>
  </div>
  <div class="field">
    <%= f.label :urlpdfpaper %><br>
    <%= f.text_field :urlpdfpaper %>
  </div>
  <div class="field">
    <%= f.label :urlsrcpaper %><br>
    <%= f.text_field :urlsrcpaper %>
  </div>
  <div class="field">
    <%= f.label :urlpdfpresentation %><br>
    <%= f.text_field :urlpdfpresentation %>
  </div>
  <div class="field">
    <%= f.label :urlsrcpresentation %><br>
    <%= f.text_field :urlsrcpresentation %>
  </div>
  <div class="field">
    <%= f.label :urlavmedia %><br>
    <%= f.text_field :urlavmedia %>
  </div>
  <div class="field">
    <%= f.label :urldoi %><br>
    <%= f.text_field :urldoi %>
  </div>
  <div class="field">
    <%= f.label :urlpublisher %><br>
    <%= f.text_field :urlpublisher %>
  </div>
  <div class="field">
    <%= f.label :urlgooglescholar %><br>
    <%= f.text_field :urlgooglescholar %>
  </div>
  <div class="field">
    <%= f.label :urlciteseer %><br>
    <%= f.text_field :urlciteseer %>
  </div>
  <div class="field">
    <%= f.label :pubin %><br>
    <%= f.text_field :pubin %>
  </div>
  <div class="field">
    <%= f.label :pubvol %><br>
    <%= f.text_field :pubvol %>
  </div>
  <div class="field">
    <%= f.label :pubnum %><br>
    <%= f.text_field :pubnum %>
  </div>
  <div class="field">
    <%= f.label :pubnum_end %><br>
    <%= f.text_field :pubnum_end %>
  </div>
  <div class="field">
    <%= f.label :pubpagefirst %><br>
    <%= f.text_field :pubpagefirst %>
  </div>
  <div class="field">
    <%= f.label :pubpagelast %><br>
    <%= f.text_field :pubpagelast %>
  </div>
  <div class="field">
    <%= f.label :pubpagecount %><br>
    <%= f.text_field :pubpagecount %>
  </div>
  <div class="field">
    <%= f.label :pubdate %><br>
    <%= f.date_select :pubdate %>
  </div>
  <div class="field">
    <%= f.label :pubdate_end %><br>
    <%= f.date_select :pubdate_end %>
  </div>
  <div class="field">
    <%= f.label :pubplace %><br>
    <%= f.text_field :pubplace %>
  </div>
  <div class="field">
    <%= f.label :publisher %><br>
    <%= f.text_field :publisher %>
  </div>
  <div class="field">
    <%= f.label :ispublic %><br>
    <%= f.check_box :ispublic %>
  </div>
  <div class="field">
    <%= f.label :islabdocument %><br>
    <%= f.check_box :islabdocument %>
  </div>
  <div class="field">
    <%= f.label :miscattributes %><br>
    <%= f.text_field :miscattributes %>
  </div>
  <div class="field">
    <%= f.label :document_category_id %><br>
    <%= f.text_field :document_category_id %>
  </div>
  <div class="field">
    <%= f.label :main_research_area_id %><br>
    <%= f.text_field :main_research_area_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/documents/edit.html.erb
<h1>Editing document</h1>

<%= render 'form' %>

<%= link_to 'Show', @document %> |
<%= link_to 'Back', documents_path %>

app/views/documents/index.html.erb
<% provide(:title, 'Documents') %>

<br>
<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading">
    <h1 class="panel-title">Documents from <%= ENV["LABACRONYM"]%></h1>
  </div>

  <div class="panel-body">
    Multiple tables, one for each document category
    <!-- Table -->
    <table class="table">
      <thead>
      <tr>
        <th>Category1</th>
        <% if user_signed_in? && current_user.admin? %>
            <th colspan="3"></th>
        <% else %>
            <th colspan="1"></th>
        <% end %>
      </tr>
      </thead>

      <tbody>
      <% @documents.each do |document| %>
          <tr>
            <td>Citation</td>
            <td><%= link_to 'Show', document %></td>
            <% if user_signed_in? && current_user.admin? %>
                <td><%= link_to 'Edit', edit_document_path(document) %></td>
                <td><%= link_to 'Destroy', document, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <% end %>
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>
  <div class="panel-footer">
    <% if user_signed_in? %>
        <% if current_user.admin? %>
            <%= link_to 'New Document', new_document_path %>
        <% end %>
    <% end %>
  </div>
</div>



<table>
  <thead>
    <tr>
      <th>Tryear</th>
      <th>Trmonth</th>
      <th>Trnumber</th>
      <th>Title</th>
      <th>Abstract</th>
      <th>Filename</th>
      <th>File</th>
      <th>Urlpdfpaper</th>
      <th>Urlsrcpaper</th>
      <th>Urlpdfpresentation</th>
      <th>Urlsrcpresentation</th>
      <th>Urlavmedia</th>
      <th>Urldoi</th>
      <th>Urlpublisher</th>
      <th>Urlgooglescholar</th>
      <th>Urlciteseer</th>
      <th>Pubin</th>
      <th>Pubvol</th>
      <th>Pubnum</th>
      <th>Pubnum end</th>
      <th>Pubpagefirst</th>
      <th>Pubpagelast</th>
      <th>Pubpagecount</th>
      <th>Pubdate</th>
      <th>Pubdate end</th>
      <th>Pubplace</th>
      <th>Publisher</th>
      <th>Ispublic</th>
      <th>Islabdocument</th>
      <th>Miscattributes</th>
      <th>Document category</th>
      <th>Main research area</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @documents.each do |document| %>
      <tr>
        <td><%= document.tryear %></td>
        <td><%= document.trmonth %></td>
        <td><%= document.trnumber %></td>
        <td><%= document.title %></td>
        <td><%= document.abstract %></td>
        <td><%= document.filename %></td>
        <td><%= document.file %></td>
        <td><%= document.urlpdfpaper %></td>
        <td><%= document.urlsrcpaper %></td>
        <td><%= document.urlpdfpresentation %></td>
        <td><%= document.urlsrcpresentation %></td>
        <td><%= document.urlavmedia %></td>
        <td><%= document.urldoi %></td>
        <td><%= document.urlpublisher %></td>
        <td><%= document.urlgooglescholar %></td>
        <td><%= document.urlciteseer %></td>
        <td><%= document.pubin %></td>
        <td><%= document.pubvol %></td>
        <td><%= document.pubnum %></td>
        <td><%= document.pubnum_end %></td>
        <td><%= document.pubpagefirst %></td>
        <td><%= document.pubpagelast %></td>
        <td><%= document.pubpagecount %></td>
        <td><%= document.pubdate %></td>
        <td><%= document.pubdate_end %></td>
        <td><%= document.pubplace %></td>
        <td><%= document.publisher %></td>
        <td><%= document.ispublic %></td>
        <td><%= document.islabdocument %></td>
        <td><%= document.miscattributes %></td>
        <td><%= document.document_category %></td>
        <td><%= document.main_research_area %></td>
        <td><%= link_to 'Show', document %></td>
        <td><%= link_to 'Edit', edit_document_path(document) %></td>
        <td><%= link_to 'Destroy', document, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/documents/new.html.erb
<h1>New document</h1>

<%= render 'form' %>

<%= link_to 'Back', documents_path %>

app/views/documents/show.html.erb
<p>
  <strong>Tryear:</strong>
  <%= @document.tryear %>
</p>

<p>
  <strong>Trmonth:</strong>
  <%= @document.trmonth %>
</p>

<p>
  <strong>Trnumber:</strong>
  <%= @document.trnumber %>
</p>

<p>
  <strong>Title:</strong>
  <%= @document.title %>
</p>

<p>
  <strong>Abstract:</strong>
  <%= @document.abstract %>
</p>

<p>
  <strong>Filename:</strong>
  <%= @document.filename %>
</p>

<p>
  <strong>File:</strong>
  <%= @document.file %>
</p>

<p>
  <strong>Urlpdfpaper:</strong>
  <%= @document.urlpdfpaper %>
</p>

<p>
  <strong>Urlsrcpaper:</strong>
  <%= @document.urlsrcpaper %>
</p>

<p>
  <strong>Urlpdfpresentation:</strong>
  <%= @document.urlpdfpresentation %>
</p>

<p>
  <strong>Urlsrcpresentation:</strong>
  <%= @document.urlsrcpresentation %>
</p>

<p>
  <strong>Urlavmedia:</strong>
  <%= @document.urlavmedia %>
</p>

<p>
  <strong>Urldoi:</strong>
  <%= @document.urldoi %>
</p>

<p>
  <strong>Urlpublisher:</strong>
  <%= @document.urlpublisher %>
</p>

<p>
  <strong>Urlgooglescholar:</strong>
  <%= @document.urlgooglescholar %>
</p>

<p>
  <strong>Urlciteseer:</strong>
  <%= @document.urlciteseer %>
</p>

<p>
  <strong>Pubin:</strong>
  <%= @document.pubin %>
</p>

<p>
  <strong>Pubvol:</strong>
  <%= @document.pubvol %>
</p>

<p>
  <strong>Pubnum:</strong>
  <%= @document.pubnum %>
</p>

<p>
  <strong>Pubnum end:</strong>
  <%= @document.pubnum_end %>
</p>

<p>
  <strong>Pubpagefirst:</strong>
  <%= @document.pubpagefirst %>
</p>

<p>
  <strong>Pubpagelast:</strong>
  <%= @document.pubpagelast %>
</p>

<p>
  <strong>Pubpagecount:</strong>
  <%= @document.pubpagecount %>
</p>

<p>
  <strong>Pubdate:</strong>
  <%= @document.pubdate %>
</p>

<p>
  <strong>Pubdate end:</strong>
  <%= @document.pubdate_end %>
</p>

<p>
  <strong>Pubplace:</strong>
  <%= @document.pubplace %>
</p>

<p>
  <strong>Publisher:</strong>
  <%= @document.publisher %>
</p>

<p>
  <strong>Ispublic:</strong>
  <%= @document.ispublic %>
</p>

<p>
  <strong>Islabdocument:</strong>
  <%= @document.islabdocument %>
</p>

<p>
  <strong>Miscattributes:</strong>
  <%= @document.miscattributes %>
</p>

<p>
  <strong>Document category:</strong>
  <%= @document.document_category %>
</p>

<p>
  <strong>Main research area:</strong>
  <%= @document.main_research_area %>
</p>

<%= link_to 'Edit', edit_document_path(@document) %> |
<%= link_to 'Back', documents_path %>